name: ensure-environment-api-connection
run-name: ${{ github.event.client_payload.dispatch_payload.current_step }}:${{ github.event.client_payload.dispatch_job_id }}

on:
  repository_dispatch:
    types: [ensure-environment-api-connection]

jobs:
  perform-service-operation:
    runs-on: windows-latest

    steps:
    - name: "OnfusionCoE: ensure-environment-api-connection Dispatch"
      uses: fusioncoe/onfusioncoe-actions-g2/ensure-environment-api-connection@v0
      with:
        client_id: ${{ vars.FUSIONCOE_SP_APPLICATION_ID }}
        client_secret: ${{ secrets.FUSIONCOE_SP_SECRET }}
        tenant_id: ${{ vars.FUSIONCOE_SP_TENANT_ID }}
        authority: ${{ vars.FUSIONCOE_SP_AUTHORITY }}        
        cloud: ${{ vars.FUSIONCOE_SP_CLOUD }}
        event_path: ${{ github.event_path }}
        output_private_key: ${{ secrets.FUSIONCOE_SP_PRIVATE_KEY }}   
